version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"           # Graphite Web UI
      - "2003:2003"       # Carbon plaintext
      - "2004:2004"       # Carbon pickle
      - "8125:8125/udp"   # StatsD
      - "8126:8126"       # StatsD admin
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - graphite
    restart: always

volumes:
  grafana-storage:
